name: Publish to FlakeHub
on:
  push:
    branches:
      - main
jobs:
  flakehub-publish:
    name: Publish to FlakeHub
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@v3.21.9
      - uses: DeterminateSystems/flakehub-push@v6
        with:
          name: rzp/den-lsp
          rolling: true
          visibility: unlisted
          include-output-paths: true