on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-pkg:
    name: Build Nix package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: DeterminateSystems/determinate-nix-action@main
      - run: nix build .